apiVersion: v1
kind: Service
metadata:
  name: abc-nodeportservice
  namespace: default
spec:
  type: NodePort
  selector:
    app: abc-webapp
  ports:
  - name: http
    port: 80
    targetPort: 80

