apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-k8s-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc-webapp
  template:
    metadata:
      labels:
        app: abc-webapp
    spec:
      containers:
      - name: my_abc_container
        image: siddharthsrivastava2688/cicd_pipeline:my_customapp-1.0
        ports:
        - containerPort: 80

