apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech
spec:
  selector:
    matchLabels:
      app: abc-tech
  template:
    metadata:
      labels:
        app: abc-tech
    spec:
      containers:
      - name: abc-tech
        image: siddharthsrivastava2688/cicd_pipeline:my_customapp-1.0
        command: ["/bin/sh"]
        args: ["-c","sh /usr/local/tomcat/bin/startup.sh;while true; do echo hello; sleep 10;done"]
        ports:
            - name: http
              containerPort: 8080
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: abc-tech-app-service
  labels:
    app: abc-tech
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 9999
    protocol: TCP
    name: http
  selector:
    app: abc-tech
